# Generated by Django 2.2.14 on 2021-04-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Articles',
        ),
    ]
