# Generated by Django 2.2.14 on 2021-04-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210409_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Artic',
        ),
    ]
