# Generated by Django 2.2.14 on 2021-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210409_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='artic',
            name='images',
            field=models.ImageField(blank=True, default='defaultimg.png', upload_to=''),
        ),
    ]
